---
allowed_instance_types:
  - c5.12xlarge
  - c5.18xlarge
  - c5.24xlarge
  - c5.2xlarge
  - c5.4xlarge
  - c5.9xlarge
  - c5.large
  - c5.metal
  - c5.xlarge
  - c5d.18xlarge
  - c5d.12xlarge
  - c5d.2xlarge
  - c5d.4xlarge
  - c5d.9xlarge
  - c5d.large
  - c5d.xlarge
  - m5.12xlarge
  - m5.16xlarge
  - m5.24xlarge
  - m5.2xlarge
  - m5.4xlarge
  - m5.8xlarge
  - m5.large
  - m5.metal
  - m5.xlarge
  - m5d.12xlarge
  - m5d.16xlarge
  - m5d.24xlarge
  - m5d.2xlarge
  - m5d.4xlarge
  - m5d.8xlarge
  - m5d.large
  - m5d.metal
  - m5d.xlarge
  - r5.12xlarge
  - r5.16xlarge
  - r5.24xlarge
  - r5.2xlarge
  - r5.4xlarge
  - r5.8xlarge
  - r5.large
  - r5.metal
  - r5.xlarge
  - r5d.12xlarge
  - r5d.16xlarge
  - r5d.24xlarge
  - r5d.2xlarge
  - r5d.4xlarge
  - r5d.8xlarge
  - r5d.large
  - r5d.metal
  - r5d.xlarge
  - t3.2xlarge
  - t3.large
  - t3.medium
  - t3.micro
  - t3.nano
  - t3.small
  - t3.xlarge
allowed_regions:
  - ap-northeast-1
  - ap-northeast-2
  - ap-south-1
  - ap-southeast-1
  - ap-southeast-2
  - ca-central-1
  - eu-central-1
  - eu-north-1
  - eu-west-1
  - eu-west-2
  - eu-west-3
  - sa-east-1
  - us-east-2
  - us-west-1
  - us-west-2
